"""
train_db.py

Training pipeline for the CNN-based RFI knee-index classifier.

Consumes the tile records written by generate_amazon_data.py (real Amazon
background, rfi_data_<freq>_<pol>.h5) and generate_mountain_rfi_data.py (real
mountain background, mountain_rfi_data_<freq>_<pol>.h5). Both file families
share the same per-tile schema -- labels, eigenvalues, and (since both
generators were updated to store it) the SCM diagonal and its per-index
validity mask -- so they load through the same function and train as one
combined pool. The SCM was already gap-excluded at generation time and its
eigenvalues stored in LINEAR scale, so this script never touches a complex
CPI tile -- it truncates, normalizes, and trains.

Standard CPI dimensions: 16 pulses x 250 range samples (M=16, K=250).

Data layout: combined training pool, two kinds of held-out test
-----------------------------------------------------------------
--data-dir accepts ONE OR MORE directories and concatenates everything found
in them into a single train+val pool (default: an Amazon run and a mountain
run together):

    --data-dir data/amazon_train data/mountain_rfi_train   -> train + val

Tiles from different directories can share a numeric tile_pulse by pure
coincidence (they are different granules / physical locations), so each
directory is folded into the train/val split key with its own offset --
see load_rfi_data_dir -- to guarantee a background from one source never ends
up split across train and val because of a coincidental index collision with
another source.

Two, independent kinds of held-out evaluation follow training:

  1. --test-dir: the ORIGINAL design. A disjoint pulse window, generated
     separately (same 0..6 band range, clean interspersed at random), so no
     test tile shares a background with training. Evaluated with the existing
     CHECK 1 / CHECK 2 (clean_check / contaminated_check) machinery.

  2. --paired-test-dir: a NEW, stronger check, generated by
     generate_mountain_rfi_data.py --paired-test. For every confirmed-clean
     mountain tile, that run writes BOTH an untouched copy and a
     forced-contaminated copy of the IDENTICAL raw CPI (see that script's
     docstring). Because both halves of a pair share one background, this
     script can directly compare model behavior on the same tile clean vs.
     RFI-overlaid, rather than across two different tiles that merely drew
     different band counts. This is the "examine the behavior" check.

     It also reports a non-ML companion signal: the SCM-diagonal jump metric.
     RFI raises the diagonal power sharply on the row(s) it occupies, so a
     contaminated tile's diagonal has a large step between an injected row
     and its clean neighbors, while a clean tile's diagonal stays
     comparatively flat. diagonal_jump_metric() computes the largest
     adjacent-row jump (dB) over the valid diagonal entries, and the paired
     check reports how well a simple percentile threshold on that jump alone
     -- no model involved -- separates clean from contaminated. The same
     metric is also reported at the population level (clean vs contaminated
     tiles, not necessarily paired) on --test-dir, whenever that data has a
     diagonal stored.

Generating the disjoint --test-dir region (use a seed distinct from the
training run, so the held-out injections are an independent realization):

    py-isce3 generate_amazon_data.py granule.h5 --freq A \\
        --pulse-start 888222 --pulse-end 896222 \\
        --range-start 2000 --range-end 25000 \\
        --compute-subswath-mask \\
        --off-diag-overlap-ratio 0.03 --diag-valid-ratio 0.02 \\
        --seed 7 --output-dir data/rfi_test

Generating the paired mountain test region:

    python generate_mountain_rfi_data.py clean_mountains_filtered.h5 granule.h5 \\
        --paired-test --max-bands 6 --mask-mode subswath \\
        --seed 7 --output-dir data/mountain_rfi_paired_test

Design decisions
----------------
1. The generating run is expected to have used very permissive gap-exclusion
   validity ratios (3% off-diagonal overlap, 2% diagonal valid) so dithered
   CPIs are preserved rather than dropped. That trades some SCM estimate
   quality for data yield; the feature normalization below is what makes the
   trade-off usable. The ratios actually used live in the file attrs and are
   echoed at load time, so a mismatch is visible instead of silent.
2. Eigenvalues are normalized on the LINEAR scale first (lambda_i / lambda_max,
   so lambda_max -> 1), THEN converted to dB. This removes absolute power level
   as a factor (dithered vs full-power CPIs), leaving spectral SHAPE as the
   signal the model learns from.
3. Only the first N_KEEP = 12 eigenvalues (the 12 largest, descending) are used
   as features. The remaining 4 (smallest) are the ones most exposed to
   dithering / dropout artifacts -- roughly 38.6% of healthy tiles show a
   >10 dB collapse in the smallest eigenvalue. Truncation happens BEFORE
   normalization, so a collapsed eigenvalue never reaches lambda_max, the dB
   floor, or the global features.
4. Condition number (dB) and effective rank are BOTH computed from the kept 12
   eigenvalues only, for every tile, clean or dithered alike, so the two global
   features stay on a consistent basis.

The model architecture is untouched. build_model is called with
cpi_size = N_KEEP, which only sets the length of the eigen-branch input;
n_knee_classes stays tied to the LABEL range, so truncating the features cannot
silently reshape the output head.

Feature extraction (per CPI tile)
---------------------------------
eigen_input  shape (N_KEEP, 2):
    channel 0 -- top N_KEEP eigenvalues, normalized by lambda_max on the linear
                 scale, then 10*log10 (so channel 0 always starts at 0 dB)
    channel 1 -- finite differences of channel 0 (slopes in dB per index),
                 zero-padded at index N_KEEP-1 so the tensor stays (N_KEEP, 2)

global_input shape (2,):
    0  condition_number_db -- ev_db[0] - ev_db[N_KEEP-1], over the kept 12
    1  eff_rank            -- Shannon-entropy effective rank, over the kept 12

Train / val split
-----------------
Split by CONTIGUOUS BLOCKS OF PULSE TILES, not by random row. Tiles at the same
tile_pulse in different polarizations are the same physical background, and
neighbouring tiles share clutter, so a random split would leak a background's
clean eigenvalue floor from train into val. Splitting on tile_pulse keeps every
co-located tile together; --split-buffer pulse tiles are dropped at the
boundary so the two sides are not immediate spatial neighbours.

Usage
-----
    python train_db.py \\
        --data-dir data/amazon_train data/mountain_rfi_train \\
        --test-dir data/rfi_test \\
        --paired-test-dir data/mountain_rfi_paired_test

Outputs
-------
    models/<run>/best_model.keras
    models/<run>/training_curves.png
    models/<run>/clean_check.png              -- check 1: predictions on clean tiles
    models/<run>/confusion_matrix.png         -- full 0..6 grid, clean row included
    models/<run>/metrics.png
    models/<run>/accuracy_vs_jsr.png
    models/<run>/diagonal_jump_hist_testregion.png  -- if --test-dir has a diagonal
    models/<run>/paired_behavior.png          -- if --paired-test-dir is given
    models/<run>/diagonal_jump_hist_paired.png      -- if --paired-test-dir is given
    models/<run>/eval_results.json
    models/<run>_summary.json
"""

import os
import sys
import glob
import json
import argparse

import numpy as np
import h5py
import tensorflow as tf

# Add project root to path to import model
project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, project_root)

from model import build_model


# ---------------------------------------------------------------------------
# CONSTANTS
# ---------------------------------------------------------------------------

MODELS_ROOT = 'models'

M = 16                 # pulses per CPI = number of eigenvalues available
N_KEEP = 12            # eigenvalues actually used as features (the 12 largest)
N_GLOBAL = 2           # global features: [condition_number_db, eff_rank]

# Permissive gap-exclusion ratios the generating run is expected to have used.
# Checked against the file attrs; the SCM itself is computed in the generator.
EXPECTED_OFF_DIAG_OVERLAP_RATIO = 0.03
EXPECTED_DIAG_VALID_RATIO = 0.02

EPOCHS = 50
BATCH_SIZE = 256
LR = 3e-4
VAL_FRAC = 0.15        # of the training region; test comes from its own region

# Pulse tiles dropped at the train/val boundary
SPLIT_BUFFER_DEFAULT = 8

EPS = 1e-12
DB_FLOOR = -100.0      # floor for dB values, guards the log of a collapsed eigenvalue

# File-name patterns for the two tile-record families this script consumes.
# The paired mountain test set is excluded from the generic glob because it
# has two rows per tile (clean + forced-contaminated) and needs its own
# loader (load_paired_test_dir) to match them back up by pair_id.
TILE_FILE_PATTERNS = ('rfi_data_*.h5', 'mountain_rfi_data_*.h5')
PAIRED_FILE_PATTERN = 'mountain_rfi_data_paired_*.h5'

# Multiplier folded into the train/val split key so that two different source
# directories (e.g. an Amazon run and a mountain run) can never collide on a
# numeric tile_pulse and be mistaken for the same physical background.
GROUP_OFFSET = 10_000_000


# ---------------------------------------------------------------------------
# FEATURE EXTRACTION
# ---------------------------------------------------------------------------

def features_from_eigenvalues(eigvals_linear):
    """
    Build the eigen and global feature tensors from LINEAR eigenvalues.

    Single place the N_KEEP truncation and normalization order are defined, so
    train and test features are guaranteed identical.

    Steps:
      1. Take the top N_KEEP eigenvalues (input is already descending). The
         bottom 4 are dropped here, before anything else touches them, so the
         dithering-induced collapse in the smallest eigenvalue cannot reach
         lambda_max or the global features.
      2. Normalize on the LINEAR scale by lambda_max, so lambda_max -> 1. This
         removes absolute power level and leaves spectral shape as the signal.
      3. Convert to dB. Channel 0 therefore always starts at exactly 0 dB.
      4. Slopes = finite differences of the dB profile, zero-padded to N_KEEP.
      5. Condition number and effective rank from the SAME kept 12.

    A gap-excluded SCM can be slightly indefinite (entries with too little valid
    overlap are zeroed), so eigenvalues are clipped at EPS before the log.

    Args:
        eigvals_linear (np.ndarray): (M,) or (N, M) real eigenvalues, descending.

    Returns:
        eigen (np.ndarray): (N_KEEP, 2) or (N, N_KEEP, 2), float32.
        global_ (np.ndarray): (N_GLOBAL,) or (N, N_GLOBAL), float32.
    """
    single = (np.asarray(eigvals_linear).ndim == 1)
    ev = np.atleast_2d(np.asarray(eigvals_linear, dtype=np.float64))

    # 1. Keep the 12 largest, drop the 4 dithering-exposed smallest
    ev = ev[:, :N_KEEP]

    # 2. Linear normalization by lambda_max (per tile)
    ev = np.maximum(ev, EPS)
    lam_max = np.maximum(ev[:, :1], EPS)
    ev_norm = ev / lam_max

    # 3. dB
    ev_db = 10.0 * np.log10(np.maximum(ev_norm, EPS))
    ev_db = np.maximum(ev_db, DB_FLOOR)

    # 4. Slopes, zero-padded so the tensor stays (N_KEEP, 2)
    slopes = np.diff(ev_db, axis=1)
    slopes = np.concatenate([slopes, np.zeros((ev_db.shape[0], 1))], axis=1)
    eigen = np.stack([ev_db, slopes], axis=-1).astype(np.float32)

    # 5. Global features, both over the kept 12 only
    cond_db = ev_db[:, 0] - np.maximum(ev_db[:, -1], DB_FLOOR)

    p = ev / np.maximum(ev.sum(axis=1, keepdims=True), EPS)
    p = np.maximum(p, EPS)
    eff_rank = np.exp(-np.sum(p * np.log(p), axis=1))

    global_ = np.stack([cond_db, eff_rank], axis=-1).astype(np.float32)

    if single:
        return eigen[0], global_[0]
    return eigen, global_


def diagonal_jump_metric(diag_lin, diag_valid_idx):
    """
    Largest jump (dB) between adjacent valid pulse rows of the SCM diagonal.

    RFI raises the diagonal power sharply on the row(s) it occupies, so a
    contaminated tile's diagonal profile has a large step between an injected
    row and its clean neighbors. A clean tile's diagonal is comparatively
    flat, so its largest adjacent jump should stay small. This is a purely
    evaluation-time diagnostic -- it is never fed into the model -- used to
    check whether RFI leaves a signature on the diagonal independent of the
    eigenvalue-based classifier.

    Invalid (gap-excluded) rows are skipped: a jump computed across a row that
    had too few valid samples is a validity artifact, not a physical jump, so
    only jumps between two BOTH-valid adjacent rows are considered.

    Args:
        diag_lin (np.ndarray): (M,) or (N, M) linear-scale SCM diagonal.
        diag_valid_idx (np.ndarray): (M,) or (N, M) bool, same shape.

    Returns:
        jump_db (float or np.ndarray): scalar or (N,) float32. NaN where fewer
            than 2 adjacent valid rows exist to form a jump.
    """
    single = (np.asarray(diag_lin).ndim == 1)
    diag = np.atleast_2d(np.asarray(diag_lin, dtype=np.float64))
    valid = np.atleast_2d(np.asarray(diag_valid_idx, dtype=bool))

    diag_db = 10.0 * np.log10(np.maximum(diag, EPS))

    diffs = np.abs(np.diff(diag_db, axis=1))
    # A step is only meaningful if BOTH endpoints were valid (non-gap) rows
    pair_valid = valid[:, :-1] & valid[:, 1:]
    diffs = np.where(pair_valid, diffs, np.nan)

    with np.errstate(invalid='ignore'):
        all_nan = np.all(np.isnan(diffs), axis=1)
        jump = np.where(all_nan, np.nan, np.nanmax(np.where(np.isnan(diffs), -np.inf, diffs), axis=1))

    jump = jump.astype(np.float32)
    if single:
        return float(jump[0])
    return jump


# ---------------------------------------------------------------------------
# DATA LOADING
# ---------------------------------------------------------------------------

def _glob_tile_files(data_dir):
    """
    Non-paired tile-record files in a directory: either the generic
    real-background naming (rfi_data_<freq>_<pol>.h5, written by
    generate_rfi_data.py / generate_amazon_data.py) or the mountain naming
    (mountain_rfi_data_<freq>_<pol>.h5, written by
    generate_mountain_rfi_data.py). Paired test files
    (mountain_rfi_data_paired_*.h5) are excluded -- those are loaded
    separately by load_paired_test_dir, since they need pair matching rather
    than a flat concatenation.
    """
    found = set()
    for pattern in TILE_FILE_PATTERNS:
        found.update(glob.glob(os.path.join(data_dir, pattern)))
    found -= set(glob.glob(os.path.join(data_dir, PAIRED_FILE_PATTERN)))
    return sorted(found)


def load_rfi_data_dir(data_dirs, max_samples=None, tag=''):
    """
    Load every tile-record file from one or more directories, concatenating
    them into a single pool. Accepts either naming family (see
    _glob_tile_files), so an Amazon run and a mountain run can be passed
    together and trained on as one combined set.

    Each channel got an independent RFI injection realization, so labels are
    uncorrelated even where two channels share a physical background. Clean
    tiles (knee = 0) are already interspersed through these files; there is
    no separate clean source.

    The SCM diagonal and its per-index validity mask are required in every
    source file (both generators write them); a file missing either dataset
    raises an error rather than being silently degraded.

    Args:
        data_dirs (str or list[str]): one or more directories to load.
        max_samples (int|None): Cap on tiles loaded per file (evenly strided).
        tag (str): Label used in the printout (e.g. 'TRAIN region').

    Returns:
        data (dict) with keys:
            eigen (N, N_KEEP, 2) float32
            global (N, N_GLOBAL) float32
            labels (N,) int32          -- knee = number of injected bands, 0 = clean
            groups (N,) int64          -- source-namespaced tile_pulse, the block-split key
            channels (N,) object       -- 'A-HH' / 'A-HV' / ...
            jsr (N, max_bands) float32 or None -- NaN-padded per-band JSR
            diagonal (N, M) float32    -- linear scale, NaN where unavailable
            diag_valid_idx (N, M) bool -- all False where unavailable
            diag_jump_db (N,) float32  -- diagonal_jump_metric()
            n_classes (int)
            meta (dict)
    """
    if isinstance(data_dirs, str):
        data_dirs = [data_dirs]

    eigen_parts, global_parts = [], []
    label_parts, group_parts, chan_parts, jsr_parts = [], [], [], []
    diag_parts, diag_valid_parts = [], []
    n_classes = 0
    meta = {'dirs': list(data_dirs), 'files': [], 'channels': [], 'pulse_window': None}

    print(f"\nLoading {tag or data_dirs} ...")

    for source_id, data_dir in enumerate(data_dirs):
        paths = _glob_tile_files(data_dir)
        if not paths:
            raise FileNotFoundError(
                f"No tile record files (rfi_data_*.h5 / mountain_rfi_data_*.h5) "
                f"found in {data_dir}"
            )

        for path in paths:
            with h5py.File(path, 'r') as f:
                n_rec = int(f.attrs.get('n_records', f['labels'].shape[0]))
                freq = str(f.attrs.get('frequency', '?'))
                pol = str(f.attrs.get('polarization', '?'))
                chan = f'{freq}-{pol}'

                odr = float(f.attrs.get('off_diag_overlap_ratio', float('nan')))
                dvr = float(f.attrs.get('diag_valid_ratio', float('nan')))
                gap = bool(f.attrs.get('gap_exclusion_used', False))
                seed = int(f.attrs.get('seed', -1))
                p0 = int(f.attrs.get('pulse_start', -1)) if 'pulse_start' in f.attrs else -1
                p1 = int(f.attrs.get('pulse_end', -1)) if 'pulse_end' in f.attrs else -1
                min_b = int(f.attrs.get('min_bands', -1))
                max_b = int(f.attrs.get('max_bands', -1))

                if 'diagonal' not in f or 'diag_valid_idx' not in f:
                    raise ValueError(
                        f"{path} has no 'diagonal'/'diag_valid_idx' dataset. "
                        f"Regenerate it with the current generate_amazon_data.py "
                        f"/ generate_mountain_rfi_data.py, both of which write these."
                    )

                sel = slice(None)
                if max_samples is not None and n_rec > max_samples:
                    stride = int(np.ceil(n_rec / max_samples))
                    sel = slice(0, n_rec, stride)

                eigvals = f['eigenvalues'][sel]              # (n, M) linear, descending
                labels = f['labels'][sel].astype(np.int32)
                groups_raw = f['tile_pulse'][sel].astype(np.int64)
                jsr = np.asarray(f['jsr_db'][sel], dtype=np.float32) if 'jsr_db' in f else None

                diag = np.asarray(f['diagonal'][sel], dtype=np.float64)
                diag_valid = np.asarray(f['diag_valid_idx'][sel], dtype=bool)

                eigen, global_ = features_from_eigenvalues(eigvals)

                eigen_parts.append(eigen)
                global_parts.append(global_)
                label_parts.append(labels)
                group_parts.append(source_id * GROUP_OFFSET + groups_raw)
                chan_parts.append(np.full(len(labels), chan, dtype=object))
                diag_parts.append(diag)
                diag_valid_parts.append(diag_valid)
                if jsr is not None:
                    jsr_parts.append(jsr)

                n_classes = max(n_classes, int(f.attrs.get('n_classes', 0)))

                print(f"  {os.path.basename(path)}: {len(labels)} tiles  "
                      f"[{chan}, pulses {p0}-{p1}, bands {min_b}..{max_b}, seed={seed}, "
                      f"gap={gap}, off_diag={odr:.2f}, diag={dvr:.2f}]")

                if min_b != 0:
                    print(f"    WARNING: min_bands={min_b}, so this set has NO clean tiles. "
                          f"Training/test sources should be generated with --min-bands 0 so "
                          f"clean data stays interspersed in the same distribution.")

                if gap and not (np.isclose(odr, EXPECTED_OFF_DIAG_OVERLAP_RATIO)
                                and np.isclose(dvr, EXPECTED_DIAG_VALID_RATIO)):
                    print(f"    NOTE: SCM validity ratios differ from the permissive "
                          f"target ({EXPECTED_OFF_DIAG_OVERLAP_RATIO}/"
                          f"{EXPECTED_DIAG_VALID_RATIO}). Dithered CPIs may have had "
                          f"SCM entries zeroed at generation time.")

                meta['files'].append(os.path.basename(path))
                if chan not in meta['channels']:
                    meta['channels'].append(chan)
                if p0 != -1:
                    meta['pulse_window'] = [p0, p1]
                meta['seed'] = seed
                meta['min_bands'] = min_b
                meta['max_bands'] = max_b
                meta['off_diag_overlap_ratio'] = odr
                meta['diag_valid_ratio'] = dvr

    labels = np.concatenate(label_parts, axis=0)
    diag_lin = np.concatenate(diag_parts, axis=0)
    diag_valid_idx = np.concatenate(diag_valid_parts, axis=0)

    diag_jump_db = diagonal_jump_metric(diag_lin, diag_valid_idx)

    return {
        'eigen': np.concatenate(eigen_parts, axis=0),
        'global': np.concatenate(global_parts, axis=0),
        'labels': labels,
        'groups': np.concatenate(group_parts, axis=0),
        'channels': np.concatenate(chan_parts, axis=0),
        'jsr': np.concatenate(jsr_parts, axis=0) if jsr_parts else None,
        'diagonal': diag_lin.astype(np.float32),
        'diag_valid_idx': diag_valid_idx,
        'diag_jump_db': diag_jump_db,
        'n_classes': n_classes or int(labels.max()) + 1,
        'meta': meta,
    }


def check_disjoint(train_meta, test_meta):
    """
    Confirm the test window does not overlap the training window.

    A shared pulse would mean a test tile's background was seen in training,
    which is what the separate-region design exists to prevent.
    """
    tp = train_meta.get('pulse_window')
    xp = test_meta.get('pulse_window')
    if not tp or not xp or -1 in tp or -1 in xp:
        return

    overlap = min(tp[1], xp[1]) - max(tp[0], xp[0])
    if overlap > 0:
        print(f"\n  WARNING: test window {xp} overlaps the training window {tp} by "
              f"{overlap} pulses. Those tiles' backgrounds were seen in training; "
              f"the held-out metrics will be optimistic.")
    else:
        print(f"  test pulses {xp} disjoint from training {tp}  OK")

    if test_meta.get('seed') == train_meta.get('seed'):
        print(f"  NOTE: the test set was generated with the same --seed as the "
              f"training set. The per-tile injection stream is keyed on the "
              f"WINDOW-RELATIVE pulse tile, so the two sets replay the same band "
              f"counts/rows/JSRs tile-for-tile. Backgrounds still differ, so this "
              f"is not label leakage, but a distinct seed gives a genuinely "
              f"independent injection realization.")


def split_train_val(groups, val_frac, buffer_tiles):
    """
    Split the training region into train / val by CONTIGUOUS pulse-tile blocks.

    No test split is carved out here: the test data comes from its own disjoint
    pulse window, loaded separately.

    Every record at a given tile_pulse -- including the same tile in another
    polarization -- lands on the same side, so a background's clean eigenvalue
    floor cannot appear in both. A buffer of pulse tiles is discarded at the
    boundary so the two sides are not immediate spatial neighbours.

    Args:
        groups (np.ndarray): (N,) tile_pulse of each record.
        val_frac (float): fraction of the pulse-tile axis held out for val.
        buffer_tiles (int): pulse tiles dropped at the boundary.

    Returns:
        idx_train, idx_val (np.ndarray of int)
    """
    uniq = np.unique(groups)          # sorted ascending
    n = len(uniq)

    n_val = int(round(val_frac * n))
    n_train = n - n_val
    if n_train <= 0 or n_val <= 0:
        raise ValueError(f'Not enough distinct pulse tiles ({n}) to split')

    train_g = uniq[:n_train]
    val_g = uniq[n_train:]

    # Drop a buffer on each side of the single internal boundary
    if buffer_tiles > 0:
        if len(train_g) > buffer_tiles:
            train_g = train_g[:-buffer_tiles]
        if len(val_g) > buffer_tiles:
            val_g = val_g[buffer_tiles:]

    idx_train = np.where(np.isin(groups, train_g))[0]
    idx_val = np.where(np.isin(groups, val_g))[0]

    print(f"\n  Train/val block split on tile_pulse (buffer={buffer_tiles} pulse tiles):")
    print(f"    train pulses [{train_g.min()}, {train_g.max()}] -> {len(idx_train)} tiles")
    print(f"    val   pulses [{val_g.min()}, {val_g.max()}] -> {len(idx_val)} tiles")

    return idx_train, idx_val


def load_paired_test_dir(test_dir, tag=''):
    """
    Load a PAIRED mountain test set written by
    generate_mountain_rfi_data.py --paired-test.

    Each channel file holds exactly two rows per source tile: one untouched
    (label 0) and one forced-contaminated (label >= 1), sharing a pair_id.
    This function splits each file into its clean and contaminated halves and
    sorts both by pair_id, so array index i refers to the SAME background
    tile under both conditions -- which is what lets the "examine the
    behavior" check compare predictions (and the diagonal jump metric) on a
    like-for-like basis instead of across two unrelated tiles.

    Args:
        test_dir (str): directory of mountain_rfi_data_paired_<freq>_<pol>.h5 files.
        tag (str): label used in the printout.

    Returns:
        dict with 'clean', 'contam' (each a dict of eigen/global/labels/
        channels/diagonal/diag_valid_idx[/jsr]) and 'meta'.
    """
    paths = sorted(glob.glob(os.path.join(test_dir, PAIRED_FILE_PATTERN)))
    if not paths:
        raise FileNotFoundError(f"No {PAIRED_FILE_PATTERN} files found in {test_dir}")

    def empty_side():
        return {'eigen': [], 'global': [], 'labels': [], 'channels': [],
                'diagonal': [], 'diag_valid_idx': [], 'jsr': []}

    clean, contam = empty_side(), empty_side()
    meta = {'dir': test_dir, 'files': [], 'channels': []}

    print(f"\nLoading {tag or test_dir} (paired test) ...")

    for path in paths:
        with h5py.File(path, 'r') as f:
            if not bool(f.attrs.get('paired_test', False)):
                print(f"    WARNING: {os.path.basename(path)} does not have "
                      f"paired_test=True; skipping")
                continue

            freq = str(f.attrs.get('frequency', '?'))
            pol = str(f.attrs.get('polarization', '?'))
            chan = f'{freq}-{pol}'

            if 'diagonal' not in f or 'diag_valid_idx' not in f:
                raise ValueError(
                    f"{path} has no 'diagonal'/'diag_valid_idx' dataset. "
                    f"Regenerate it with the current generate_mountain_rfi_data.py, "
                    f"which writes these."
                )

            labels = f['labels'][:].astype(np.int32)
            pair_id = f['pair_id'][:].astype(np.int64)
            eigvals = f['eigenvalues'][:]
            diag = np.asarray(f['diagonal'][:], dtype=np.float64)
            diag_valid = np.asarray(f['diag_valid_idx'][:], dtype=bool)
            jsr = np.asarray(f['jsr_db'][:], dtype=np.float32) if 'jsr_db' in f else None

            is_clean = (labels == 0)
            is_contam = ~is_clean

            order_clean = np.argsort(pair_id[is_clean])
            order_contam = np.argsort(pair_id[is_contam])
            pid_clean = pair_id[is_clean][order_clean]
            pid_contam = pair_id[is_contam][order_contam]

            if not np.array_equal(pid_clean, pid_contam):
                common = np.intersect1d(pid_clean, pid_contam)
                print(f"    NOTE: {os.path.basename(path)} pair_id mismatch "
                      f"(clean={len(pid_clean)}, contam={len(pid_contam)}); "
                      f"using {len(common)} matched pairs")
                order_clean = order_clean[np.isin(pid_clean, common)]
                order_contam = order_contam[np.isin(pid_contam, common)]

            idx_clean = np.where(is_clean)[0][order_clean]
            idx_contam = np.where(is_contam)[0][order_contam]

            eigen_c, global_c = features_from_eigenvalues(eigvals[idx_clean])
            eigen_x, global_x = features_from_eigenvalues(eigvals[idx_contam])

            clean['eigen'].append(eigen_c)
            clean['global'].append(global_c)
            clean['labels'].append(labels[idx_clean])
            clean['channels'].append(np.full(len(idx_clean), chan, dtype=object))
            contam['eigen'].append(eigen_x)
            contam['global'].append(global_x)
            contam['labels'].append(labels[idx_contam])
            contam['channels'].append(np.full(len(idx_contam), chan, dtype=object))

            clean['diagonal'].append(diag[idx_clean])
            clean['diag_valid_idx'].append(diag_valid[idx_clean])
            contam['diagonal'].append(diag[idx_contam])
            contam['diag_valid_idx'].append(diag_valid[idx_contam])

            if jsr is not None:
                contam['jsr'].append(jsr[idx_contam])

            meta['files'].append(os.path.basename(path))
            if chan not in meta['channels']:
                meta['channels'].append(chan)

            print(f"  {os.path.basename(path)}: {len(idx_clean)} matched pairs  [{chan}]")

    def finalize(side):
        out = {
            'eigen': np.concatenate(side['eigen'], axis=0),
            'global': np.concatenate(side['global'], axis=0),
            'labels': np.concatenate(side['labels'], axis=0),
            'channels': np.concatenate(side['channels'], axis=0),
            'diagonal': np.concatenate(side['diagonal'], axis=0).astype(np.float32),
            'diag_valid_idx': np.concatenate(side['diag_valid_idx'], axis=0),
        }
        out['jsr'] = np.concatenate(side['jsr'], axis=0) if side.get('jsr') else None
        return out

    return {'clean': finalize(clean), 'contam': finalize(contam), 'meta': meta}


# ---------------------------------------------------------------------------
# PLOTS
# ---------------------------------------------------------------------------

def save_training_curves_png(history, out_dir):
    """Loss and accuracy vs epoch -> out_dir/training_curves.png."""
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt

    epochs = range(1, len(history.history['loss']) + 1)
    fig, (ax_loss, ax_acc) = plt.subplots(1, 2, figsize=(12, 4))

    ax_loss.plot(epochs, history.history['loss'], label='Train loss')
    ax_loss.plot(epochs, history.history['val_loss'], label='Val loss')
    ax_loss.set_xlabel('Epoch')
    ax_loss.set_ylabel('Loss')
    ax_loss.set_title('Training & Validation Loss')
    ax_loss.legend()
    ax_loss.grid(True, linestyle='--', alpha=0.5)

    acc_key = 'acc' if 'acc' in history.history else 'sparse_categorical_accuracy'
    val_acc_key = ('val_acc' if 'val_acc' in history.history
                   else 'val_sparse_categorical_accuracy')
    ax_acc.plot(epochs, history.history[acc_key], label='Train acc')
    ax_acc.plot(epochs, history.history[val_acc_key], label='Val acc')
    ax_acc.set_xlabel('Epoch')
    ax_acc.set_ylabel('Accuracy')
    ax_acc.set_title('Training & Validation Accuracy')
    ax_acc.legend()
    ax_acc.grid(True, linestyle='--', alpha=0.5)

    fig.tight_layout()
    path = os.path.join(out_dir, 'training_curves.png')
    fig.savefig(path, dpi=150)
    plt.close(fig)
    print(f"  Saved {path}")


def save_clean_check_png(pred_clean, channels_clean, n_classes, out_dir):
    """
    CHECK 1 figure: prediction histogram on the clean tiles -> clean_check.png.

    Every tile here is real, unmodified data, so the correct answer is knee = 0
    for all of them. The bar over "clean" is the recall; everything to the right
    of it is a false positive. Split per channel, since HH and HV have different
    backscatter floors and can fail very differently.
    """
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt

    chans = sorted(set(channels_clean.tolist()))
    x = np.arange(n_classes)
    width = 0.8 / max(len(chans), 1)

    fig, ax = plt.subplots(figsize=(9, 4.5))

    for i, ch in enumerate(chans):
        sel = (channels_clean == ch)
        counts = np.bincount(pred_clean[sel], minlength=n_classes)[:n_classes]
        frac = counts / max(counts.sum(), 1)
        ax.bar(x + i * width - 0.4 + width / 2, frac, width, label=f'{ch} (n={int(sel.sum())})')

    ax.set_xticks(x)
    ax.set_xticklabels(['clean'] + [f'knee@{k}' for k in range(1, n_classes)])
    ax.set_ylabel('Fraction of clean tiles')
    ax.set_xlabel('Predicted class')
    ax.set_ylim(0, 1.02)
    ax.grid(True, axis='y', linestyle='--', alpha=0.5)
    ax.legend()
    ax.set_title('Check 1: predictions on CLEAN tiles (unmodified data)\n'
                 'every tile is truly clean; anything right of "clean" is a false positive')

    fig.tight_layout()
    path = os.path.join(out_dir, 'clean_check.png')
    fig.savefig(path, dpi=150)
    plt.close(fig)
    print(f"  Saved {path}")


def save_confusion_matrix_png(y_true, y_pred, n_classes, out_dir, title):
    """
    Row-normalised knee confusion matrix -> out_dir/confusion_matrix.png.

    The full 0..6 grid, clean row included: clean tiles are interspersed in the
    test set like any other class, so clean recall and the false-positive rate
    are just row 0 of this matrix.
    """
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt

    names = ['clean'] + [f'knee@{k}' for k in range(1, n_classes)]

    matrix = np.zeros((n_classes, n_classes), dtype=np.int32)
    for t, p in zip(y_true.tolist(), y_pred.tolist()):
        matrix[t, p] += 1

    normed = matrix / matrix.sum(axis=1, keepdims=True).clip(min=1)

    fig, ax = plt.subplots(figsize=(max(7, n_classes), max(6, n_classes * 0.9)))
    im = ax.imshow(normed, vmin=0.0, vmax=1.0, cmap='Blues')
    fig.colorbar(im, ax=ax, label='Recall (row-normalised)')

    ax.set_xticks(range(n_classes))
    ax.set_yticks(range(n_classes))
    ax.set_xticklabels(names, rotation=45, ha='right', fontsize=9)
    ax.set_yticklabels(names, fontsize=9)
    ax.set_xlabel('Predicted')
    ax.set_ylabel('True')
    ax.set_title(title)

    for ri in range(n_classes):
        for ci in range(n_classes):
            color = 'white' if normed[ri, ci] > 0.5 else 'black'
            ax.text(ci, ri, str(matrix[ri, ci]), ha='center', va='center',
                    fontsize=7, color=color)

    fig.tight_layout()
    path = os.path.join(out_dir, 'confusion_matrix.png')
    fig.savefig(path, dpi=150)
    plt.close(fig)
    print(f"  Saved {path}")


def save_metrics_png(results, out_dir):
    """Bar chart of the scalar metrics -> out_dir/metrics.png."""
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt

    names, values = [], []
    for label, key in (
        ('Overall exact', 'exact_acc'),
        ('Overall tol-1', 'tol1_acc'),
        ('Check 1: clean recall', 'clean_recall'),
        ('Check 2: RFI exact', 'exact_rfi'),
        ('Check 2: RFI tol-1', 'tol1_rfi'),
        ('Check 2: detection rate', 'detection_rate'),
    ):
        if key in results and results[key] == results[key]:   # skip NaN
            names.append(label)
            values.append(results[key])

    if not names:
        return

    fig, ax = plt.subplots(figsize=(7.5, 4.5))
    bars = ax.barh(names, values, color='steelblue')
    ax.set_xlim(0, 1.05)
    ax.set_xlabel('Value')
    ax.set_title(f"Held-out metrics  --  {results['run']}\n"
                 f"test pulses {results.get('test_pulse_window')}  |  "
                 f"N={results['n_test']}  |  top {N_KEEP} eigenvalues")
    ax.grid(True, axis='x', linestyle='--', alpha=0.5)

    for bar, val in zip(bars, values):
        ax.text(min(val + 0.01, 1.0), bar.get_y() + bar.get_height() / 2,
                f'{val:.4f}', va='center', fontsize=9)

    fig.tight_layout()
    path = os.path.join(out_dir, 'metrics.png')
    fig.savefig(path, dpi=150)
    plt.close(fig)
    print(f"  Saved {path}")


def save_accuracy_vs_jsr_png(y_true, y_pred, jsr, out_dir):
    """
    Exact accuracy vs the WEAKEST band's realized JSR, contaminated tiles only
    -> out_dir/accuracy_vs_jsr.png.

    Bands draw independent JSRs from [3, 30] dB, so a knee=3 tile whose weakest
    band landed at 4 dB is a far harder sample than one whose bands all landed
    at 25 dB: the weak band barely lifts its eigenvalue off the clutter floor,
    making the tile look like a lower knee. A single aggregate accuracy hides
    this; binning by minimum band JSR shows where the model actually fails.
    """
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt

    if jsr is None:
        return

    rfi = y_true > 0
    if not rfi.any():
        return

    with np.errstate(invalid='ignore'):
        min_jsr = np.nanmin(jsr[rfi], axis=1)

    finite = np.isfinite(min_jsr)
    if not finite.any():
        return

    min_jsr = min_jsr[finite]
    correct = (y_pred[rfi][finite] == y_true[rfi][finite])

    edges = np.arange(np.floor(min_jsr.min()), np.ceil(min_jsr.max()) + 3.0, 3.0)
    centers, accs, counts = [], [], []
    for lo, hi in zip(edges[:-1], edges[1:]):
        sel = (min_jsr >= lo) & (min_jsr < hi)
        if sel.sum() < 20:
            continue
        centers.append(0.5 * (lo + hi))
        accs.append(float(correct[sel].mean()))
        counts.append(int(sel.sum()))

    if not centers:
        return

    fig, ax = plt.subplots(figsize=(8, 4.5))
    ax.plot(centers, accs, 'o-', color='steelblue')
    ax.set_xlabel('Weakest band JSR in the tile (dB)')
    ax.set_ylabel('Exact knee accuracy')
    ax.set_ylim(0, 1.02)
    ax.grid(True, linestyle='--', alpha=0.5)
    ax.set_title('Accuracy vs realized RFI strength (contaminated test tiles)')

    for x, y, c in zip(centers, accs, counts):
        ax.annotate(f'n={c}', (x, y), textcoords='offset points',
                    xytext=(0, 7), ha='center', fontsize=7)

    fig.tight_layout()
    path = os.path.join(out_dir, 'accuracy_vs_jsr.png')
    fig.savefig(path, dpi=150)
    plt.close(fig)
    print(f"  Saved {path}")


def save_diagonal_jump_hist_png(jump_clean, jump_contam, threshold, out_dir, filename, title_suffix=''):
    """
    Histogram comparing the SCM-diagonal jump metric, clean vs contaminated
    -> out_dir/filename.

    jump_clean / jump_contam are already-finite (N,) arrays in dB, as
    returned by diagonal_jump_metric with NaNs filtered out.
    """
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(figsize=(8, 4.5))
    hi = max(np.percentile(jump_contam, 99), np.percentile(jump_clean, 99), 1.0)
    bins = np.linspace(0, hi, 40)

    ax.hist(jump_clean, bins=bins, alpha=0.6, density=True, color='steelblue',
           label=f'clean (n={len(jump_clean)})')
    ax.hist(jump_contam, bins=bins, alpha=0.6, density=True, color='indianred',
           label=f'contaminated (n={len(jump_contam)})')
    ax.axvline(threshold, color='black', linestyle='--', linewidth=1.2,
              label=f'95th pct clean = {threshold:.1f} dB')

    ax.set_xlabel('Max adjacent SCM diagonal jump (dB)')
    ax.set_ylabel('Density')
    ax.set_title(f'Diagonal jump metric: clean vs. RFI-overlaid{title_suffix}\n'
                'RFI raises specific rows sharply; clean stays flat')
    ax.legend()
    ax.grid(True, linestyle='--', alpha=0.4)

    fig.tight_layout()
    path = os.path.join(out_dir, filename)
    fig.savefig(path, dpi=150)
    plt.close(fig)
    print(f"  Saved {path}")


def save_paired_behavior_png(results, out_dir):
    """Bar chart of the paired same-tile behavior metrics -> paired_behavior.png."""
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt

    names, values = [], []
    for label, key in (
        ('Clean-side recall', 'paired_clean_recall'),
        ('Contam exact acc', 'paired_exact_acc'),
        ('Contam tol-1 acc', 'paired_tol1_acc'),
        ('Contam detection', 'paired_detection_rate'),
        ('Joint success', 'paired_joint_success_rate'),
        ('Diag-jump-only detection', 'diag_jump_detection_rate'),
    ):
        if key in results and results[key] == results[key]:   # skip NaN
            names.append(label)
            values.append(results[key])

    if not names:
        return

    fig, ax = plt.subplots(figsize=(7.5, 4.5))
    bars = ax.barh(names, values, color='darkseagreen')
    ax.set_xlim(0, 1.05)
    ax.set_xlabel('Value')
    ax.set_title(f"Paired same-tile behavior (clean vs. RFI-overlaid)  "
                f"n={results.get('paired_n')}")
    ax.grid(True, axis='x', linestyle='--', alpha=0.5)

    for bar, val in zip(bars, values):
        ax.text(min(val + 0.01, 1.0), bar.get_y() + bar.get_height() / 2,
                f'{val:.4f}', va='center', fontsize=9)

    fig.tight_layout()
    path = os.path.join(out_dir, 'paired_behavior.png')
    fig.savefig(path, dpi=150)
    plt.close(fig)
    print(f"  Saved {path}")


# ---------------------------------------------------------------------------
# EVALUATION
# ---------------------------------------------------------------------------

def clean_check(y_true, y_pred, channels, n_classes, out_dir, results):
    """
    CHECK 1 -- clean data: does the model leave untouched tiles alone?

    Runs on the label == 0 subset of the test region: real CPI tiles that drew
    zero bands and were therefore never modified. The correct answer for every
    one of them is knee = 0, so the only thing being measured here is the
    false-positive rate.

    Reported per channel because HH and HV have very different backscatter
    floors, and a model can easily be clean-safe on one while triggering
    constantly on the other -- an aggregate number would average that away.

    Also records WHERE the false positives land: a model that mostly errs to
    knee@1 is far healthier than one that errs to knee@6.

    Args:
        y_true, y_pred (np.ndarray): (N,) over the FULL test set.
        channels (np.ndarray): (N,) channel name per tile.
        n_classes (int): label space size.
        out_dir (str): output directory.
        results (dict): mutated in place with the clean metrics.
    """
    clean = (y_true == 0)

    if not clean.any():
        print("\n=== CHECK 1: CLEAN DATA ===")
        print("  SKIPPED: the test set contains no clean tiles. It should have been "
              "generated with --min-bands 0 so clean tiles stay interspersed.")
        results['clean_recall'] = float('nan')
        results['false_positive_rate'] = float('nan')
        return

    pred_clean = y_pred[clean]
    n = int(clean.sum())

    recall = float(np.mean(pred_clean == 0))
    fpr = float(np.mean(pred_clean > 0))

    per_channel = {}
    for ch in sorted(set(channels.tolist())):
        sel = clean & (channels == ch)
        if sel.any():
            per_channel[ch] = {
                'n': int(sel.sum()),
                'clean_recall': float(np.mean(y_pred[sel] == 0)),
                'false_positive_rate': float(np.mean(y_pred[sel] > 0)),
            }

    fp_counts = np.bincount(pred_clean[pred_clean > 0], minlength=n_classes)[:n_classes]
    fp_dist = {str(k): int(v) for k, v in enumerate(fp_counts) if k > 0 and v > 0}

    results['clean_n'] = n
    results['clean_recall'] = recall
    results['false_positive_rate'] = fpr
    results['clean_per_channel'] = per_channel
    results['clean_false_positive_distribution'] = fp_dist

    print("\n=== CHECK 1: CLEAN DATA (unmodified tiles, knee = 0) ===")
    print(f"  N clean tiles  : {n}")
    print(f"  Clean recall   : {recall:.4f}   <- fraction correctly called clean")
    print(f"  False positives: {fpr:.4f}")
    for ch, s in per_channel.items():
        print(f"    {ch}: recall={s['clean_recall']:.4f}  FPR={s['false_positive_rate']:.4f}  "
              f"(n={s['n']})")
    if fp_dist:
        print("  False positives land on: "
              + ", ".join(f"knee@{k}:{v}" for k, v in fp_dist.items()))

    save_clean_check_png(pred_clean, channels[clean], n_classes, out_dir)


def contaminated_check(y_true, y_pred, channels, jsr, n_classes, out_dir, results):
    """
    CHECK 2 -- contaminated data: does the model count the bands correctly?

    Runs on the label > 0 subset of the test region. Reports the counting task
    (exact / tol-1 knee accuracy) and the detection task (contaminated called
    contaminated at all) separately, because a model can be a strong detector
    while still confusing adjacent knee counts -- and only the detection number
    matters if the downstream use is "flag this CPI for mitigation".

    Per-class rows include called_clean, the miss mode that actually hurts: an
    RFI tile silently passed through as clean.

    Args:
        y_true, y_pred (np.ndarray): (N,) over the FULL test set.
        channels (np.ndarray): (N,) channel name per tile.
        jsr (np.ndarray|None): (N, max_bands) realized per-band JSR.
        n_classes (int): label space size.
        out_dir (str): output directory.
        results (dict): mutated in place with the contaminated metrics.
    """
    rfi = (y_true > 0)

    if not rfi.any():
        print("\n=== CHECK 2: CONTAMINATED DATA ===")
        print("  SKIPPED: the test set contains no contaminated tiles.")
        return

    exact = float(np.mean(y_pred[rfi] == y_true[rfi]))
    tol1 = float(np.mean(np.abs(y_pred[rfi] - y_true[rfi]) <= 1))
    detection = float(np.mean(y_pred[rfi] > 0))
    missed = float(np.mean(y_pred[rfi] == 0))

    per_class = {}
    for k in range(1, n_classes):
        sel = (y_true == k)
        if sel.any():
            per_class[str(k)] = {
                'n': int(sel.sum()),
                'recall': float(np.mean(y_pred[sel] == k)),
                'tol1': float(np.mean(np.abs(y_pred[sel] - k) <= 1)),
                'called_clean': float(np.mean(y_pred[sel] == 0)),
            }

    per_channel = {}
    for ch in sorted(set(channels.tolist())):
        sel = rfi & (channels == ch)
        if sel.any():
            per_channel[ch] = {
                'n': int(sel.sum()),
                'exact_acc': float(np.mean(y_pred[sel] == y_true[sel])),
                'tol1_acc': float(np.mean(np.abs(y_pred[sel] - y_true[sel]) <= 1)),
                'detection_rate': float(np.mean(y_pred[sel] > 0)),
            }

    results['rfi_n'] = int(rfi.sum())
    results['exact_rfi'] = exact
    results['tol1_rfi'] = tol1
    results['detection_rate'] = detection
    results['missed_as_clean'] = missed
    results['rfi_per_class'] = per_class
    results['rfi_per_channel'] = per_channel

    print(f"\n=== CHECK 2: CONTAMINATED DATA (knee 1..{n_classes - 1}) ===")
    print(f"  N RFI tiles    : {int(rfi.sum())}")
    print(f"  Exact knee acc : {exact:.4f}")
    print(f"  Tol-1 knee acc : {tol1:.4f}")
    print(f"  Detection rate : {detection:.4f}   <- called contaminated at all")
    print(f"  Missed as clean: {missed:.4f}")
    for k, s in per_class.items():
        print(f"    knee@{k}: recall={s['recall']:.3f}  tol1={s['tol1']:.3f}  "
              f"called clean={s['called_clean']:.3f}  (n={s['n']})")
    for ch, s in per_channel.items():
        print(f"    {ch}: exact={s['exact_acc']:.4f}  tol1={s['tol1_acc']:.4f}  "
              f"detection={s['detection_rate']:.4f}")

    save_accuracy_vs_jsr_png(y_true, y_pred, jsr, out_dir)


def diagonal_jump_check(data, out_dir, results):
    """
    Population-level SCM-diagonal jump check on a standard test region:
    clean tiles (label 0) vs. contaminated tiles (label > 0), NOT necessarily
    the same background pair-for-pair -- that stronger check is
    paired_behavior_check, run on --paired-test-dir instead.

    This is a non-ML companion signal: RFI should produce a much larger
    adjacent-row jump on the diagonal than a clean tile's comparatively flat
    profile.

    Args:
        data (dict): output of load_rfi_data_dir on the test region.
        out_dir (str): output directory.
        results (dict): mutated in place with the jump metrics.
    """
    y_true = data['labels']
    jump = data['diag_jump_db']

    clean_sel = (y_true == 0) & np.isfinite(jump)
    contam_sel = (y_true > 0) & np.isfinite(jump)

    if not clean_sel.any() or not contam_sel.any():
        print("\n=== DIAGONAL JUMP CHECK (population-level) ===")
        print("  SKIPPED: not enough finite jump values on one side (clean/contaminated).")
        return

    jump_clean = jump[clean_sel]
    jump_contam = jump[contam_sel]
    threshold = float(np.percentile(jump_clean, 95))
    jump_detection_rate = float(np.mean(jump_contam > threshold))

    results['test_diag_jump_clean_mean_db'] = float(np.mean(jump_clean))
    results['test_diag_jump_clean_median_db'] = float(np.median(jump_clean))
    results['test_diag_jump_contam_mean_db'] = float(np.mean(jump_contam))
    results['test_diag_jump_contam_median_db'] = float(np.median(jump_contam))
    results['test_diag_jump_threshold_db'] = threshold
    results['test_diag_jump_detection_rate'] = jump_detection_rate

    print("\n=== DIAGONAL JUMP CHECK (population-level, test region) ===")
    print(f"  N clean={int(clean_sel.sum())}  N contaminated={int(contam_sel.sum())}")
    print(f"  clean  jump (dB): mean={np.mean(jump_clean):.2f}  median={np.median(jump_clean):.2f}")
    print(f"  contam jump (dB): mean={np.mean(jump_contam):.2f}  median={np.median(jump_contam):.2f}")
    print(f"  threshold (95th pct of clean) = {threshold:.2f} dB "
          f"-> flags {jump_detection_rate:.4f} of contaminated tiles on the "
          f"diagonal jump ALONE, no model involved")

    save_diagonal_jump_hist_png(jump_clean, jump_contam, threshold, out_dir,
                                filename='diagonal_jump_hist_testregion.png',
                                title_suffix=' (test region, not necessarily paired)')


def paired_behavior_check(model, paired_data, out_dir, results):
    """
    "Examine the behavior": the SAME background mountain tile, once left
    clean and once with RFI forced onto it (generate_mountain_rfi_data.py
    --paired-test). Because both halves share one background, this directly
    measures whether adding RFI flips the model's call on that exact tile,
    rather than comparing across two different tiles that happened to draw
    different band counts.

    Also reports the SCM-diagonal jump metric on the same pairs, as an
    independent, non-ML companion signal.

    Args:
        model: trained Keras model.
        paired_data (dict): output of load_paired_test_dir.
        out_dir (str): output directory.
        results (dict): mutated in place with the paired metrics.

    Returns:
        results (dict)
    """
    clean = paired_data['clean']
    contam = paired_data['contam']
    n_pairs = len(clean['labels'])

    print(f"\n=== PAIRED CHECK: SAME-TILE CLEAN vs. RFI-OVERLAID (n={n_pairs} pairs) ===")

    if n_pairs == 0:
        print("  SKIPPED: no matched pairs in the paired test set.")
        return results

    pred_clean = np.argmax(
        model.predict([clean['eigen'], clean['global']], verbose=0), axis=-1
    )
    pred_contam = np.argmax(
        model.predict([contam['eigen'], contam['global']], verbose=0), axis=-1
    )
    y_true_contam = contam['labels']

    clean_recall = float(np.mean(pred_clean == 0))
    exact_contam = float(np.mean(pred_contam == y_true_contam))
    tol1_contam = float(np.mean(np.abs(pred_contam - y_true_contam) <= 1))
    detection_rate = float(np.mean(pred_contam > 0))
    joint_rate = float(np.mean((pred_clean == 0) & (pred_contam > 0)))

    results['paired_n'] = int(n_pairs)
    results['paired_clean_recall'] = clean_recall
    results['paired_exact_acc'] = exact_contam
    results['paired_tol1_acc'] = tol1_contam
    results['paired_detection_rate'] = detection_rate
    results['paired_joint_success_rate'] = joint_rate

    print(f"  Clean-side recall      : {clean_recall:.4f}   <- same tile, untouched")
    print(f"  Contaminated exact acc : {exact_contam:.4f}   <- same tile, RFI forced onto it")
    print(f"  Contaminated tol-1 acc : {tol1_contam:.4f}")
    print(f"  Contaminated detection : {detection_rate:.4f}")
    print(f"  Joint success (both)   : {joint_rate:.4f}   <- clean stayed clean AND RFI "
          f"got flagged, on the SAME background")

    jump_clean = diagonal_jump_metric(clean['diagonal'], clean['diag_valid_idx'])
    jump_contam = diagonal_jump_metric(contam['diagonal'], contam['diag_valid_idx'])

    finite_clean = jump_clean[np.isfinite(jump_clean)]
    finite_contam = jump_contam[np.isfinite(jump_contam)]

    if len(finite_clean) and len(finite_contam):
        threshold = float(np.percentile(finite_clean, 95))
        jump_detection_rate = float(np.mean(finite_contam > threshold))

        results['diag_jump_clean_mean_db'] = float(np.mean(finite_clean))
        results['diag_jump_clean_median_db'] = float(np.median(finite_clean))
        results['diag_jump_contam_mean_db'] = float(np.mean(finite_contam))
        results['diag_jump_contam_median_db'] = float(np.median(finite_contam))
        results['diag_jump_threshold_db'] = threshold
        results['diag_jump_detection_rate'] = jump_detection_rate

        print(f"\n  SCM diagonal jump metric (dB, max adjacent step over valid rows), "
              f"SAME tiles as above:")
        print(f"    clean  : mean={np.mean(finite_clean):.2f}  median={np.median(finite_clean):.2f}")
        print(f"    contam : mean={np.mean(finite_contam):.2f}  median={np.median(finite_contam):.2f}")
        print(f"    threshold (95th pct of clean) = {threshold:.2f} dB "
              f"-> flags {jump_detection_rate:.4f} of contaminated tiles on the "
              f"diagonal jump ALONE, no model involved")

        save_diagonal_jump_hist_png(finite_clean, finite_contam, threshold, out_dir,
                                    filename='diagonal_jump_hist_paired.png',
                                    title_suffix=' (paired, same tile)')
    else:
        print("  Diagonal jump metric: not enough finite values to report.")

    save_paired_behavior_png(results, out_dir)

    return results


def evaluate(model, data, n_classes, run_name, out_dir):
    """
    Evaluate on the held-out test region, as TWO explicit checks.

    The test set contains both kinds of tile -- clean ones are simply those that
    drew 0 bands -- so a single forward pass covers both, and the two checks are
    two views of the same predictions:

        CHECK 1  clean data        -> can it leave untouched tiles alone?
        CHECK 2  contaminated data -> can it count the bands?

    The confusion matrix spans the full 0..n_classes grid, so both checks are
    also visible there: row 0 is the clean check, rows 1..6 the contaminated one.

    Args:
        model: trained Keras model.
        data (dict): output of load_rfi_data_dir on the test dir.
        n_classes (int): label space size, taken from the TRAINING set.
        run_name (str): used in figure titles.
        out_dir (str): output directory.

    Returns:
        results (dict)
    """
    y_true = data['labels']
    y_pred = np.argmax(model.predict([data['eigen'], data['global']], verbose=0),
                       axis=-1)
    channels = data['channels']

    results = {
        'run': run_name,
        'n_test': int(len(y_true)),
        'n_keep': N_KEEP,
        'n_classes': n_classes,
        'test_pulse_window': data['meta'].get('pulse_window'),
        # Overall, across clean and contaminated together
        'exact_acc': float(np.mean(y_pred == y_true)),
        'tol1_acc': float(np.mean(np.abs(y_pred - y_true) <= 1)),
    }

    print(f"\n{'='*60}")
    print(f"HELD-OUT TEST REGION  pulses {data['meta'].get('pulse_window')}")
    print(f"  N tiles: {len(y_true)}   features: top {N_KEEP} eigenvalues")
    print(f"  Overall exact: {results['exact_acc']:.4f}   "
          f"tol-1: {results['tol1_acc']:.4f}")
    print(f"{'='*60}")

    clean_check(y_true, y_pred, channels, n_classes, out_dir, results)
    contaminated_check(y_true, y_pred, channels, data['jsr'], n_classes,
                       out_dir, results)
    diagonal_jump_check(data, out_dir, results)

    print("\n  Saving confusion matrix and metrics ...")
    save_confusion_matrix_png(
        y_true, y_pred, n_classes, out_dir,
        f"Knee Confusion Matrix -- held-out region "
        f"(pulses {data['meta'].get('pulse_window')})\n"
        f"row 0 = clean check, rows 1+ = contaminated check",
    )
    save_metrics_png(results, out_dir)

    return results


# ---------------------------------------------------------------------------
# TRAINING
# ---------------------------------------------------------------------------

def train_model(run_name, n_classes,
                eigen_train, global_train, y_train,
                eigen_val, global_val, y_val,
                epochs, batch_size):
    """
    Build and train the model on the training region, validating on the held-out
    pulse-tile block of that same region.

    The architecture is untouched: build_model is called with cpi_size = N_KEEP,
    which only sets the eigen-branch input length. n_knee_classes is passed
    explicitly from the data, so truncating the features to 12 does not resize
    the output head (its default would otherwise become cpi_size + 1 = 13).

    Returns:
        model, out_dir
    """
    out_dir = os.path.join(MODELS_ROOT, run_name)
    os.makedirs(out_dir, exist_ok=True)
    model_path = os.path.join(out_dir, 'best_model.keras')

    print(f"\n{'='*60}")
    print(f"Run : {run_name}")
    print(f"  train={len(y_train)}  val={len(y_val)}")
    print(f"  eigen input : ({N_KEEP}, 2)   global: ({N_GLOBAL},)   classes: {n_classes}")
    print(f"{'='*60}")

    model = build_model(
        cpi_size=N_KEEP,                # feature length, not the pulse count
        n_global_features=N_GLOBAL,
        n_knee_classes=n_classes,       # stays tied to the label range
        dropout_rate=0.5,
        learning_rate=LR,
    )

    callbacks = [
        tf.keras.callbacks.ModelCheckpoint(
            filepath=model_path, monitor='val_loss',
            save_best_only=True, verbose=1,
        ),
        tf.keras.callbacks.EarlyStopping(
            monitor='val_loss', patience=10,
            restore_best_weights=True, verbose=1,
        ),
        tf.keras.callbacks.ReduceLROnPlateau(
            monitor='val_loss', factor=0.5, patience=5,
            min_lr=1e-6, verbose=1,
        ),
    ]

    model.fit(
        x=[eigen_train, global_train],
        y=y_train,
        validation_data=([eigen_val, global_val], y_val),
        epochs=epochs,
        batch_size=batch_size,
        callbacks=callbacks,
        verbose=2,
    )

    save_training_curves_png(model.history, out_dir)
    return model, out_dir


# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------

def parse_args():
    parser = argparse.ArgumentParser(
        description=(f'Train the RFI knee classifier on tile records from '
                     f'generate_amazon_data.py and generate_mountain_rfi_data.py '
                     f'(top {N_KEEP} eigenvalues). Train and val come from the '
                     f'combined --data-dir pool; two independent held-out checks '
                     f'follow: a disjoint-window --test-dir, and a paired same-tile '
                     f'--paired-test-dir with a SCM-diagonal jump metric.'),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument('--data-dir', type=str, nargs='+',
                        default=['data/amazon_train', 'data/mountain_rfi_train'],
                        help='One or more training directories, concatenated into a '
                             'single train+val pool. Accepts rfi_data_<freq>_<pol>.h5 '
                             '(generate_amazon_data.py / generate_rfi_data.py) and '
                             'mountain_rfi_data_<freq>_<pol>.h5 (generate_mountain_rfi_data.py).')
    parser.add_argument('--test-dir', type=str, default='data/rfi_test',
                        help='Disjoint-window held-out region, same band range, '
                             'clean interspersed. Original CHECK 1 / CHECK 2 evaluation.')
    parser.add_argument('--paired-test-dir', type=str, default='data/mountain_rfi_paired_test',
                        help='PAIRED mountain test region from generate_mountain_rfi_data.py '
                             '--paired-test: same background, clean vs. RFI-overlaid. '
                             'Skipped with a note if the directory has no matching files.')
    parser.add_argument('--run-name', type=str, default=None,
                        help='Model output folder. Defaults to the first data dir name.')
    parser.add_argument('--max-samples', type=int, default=None,
                        help='Cap tiles loaded per file (evenly strided), for quick runs.')
    parser.add_argument('--val-frac', type=float, default=VAL_FRAC,
                        help='Fraction of training-region pulse tiles held out for val.')
    parser.add_argument('--split-buffer', type=int, default=SPLIT_BUFFER_DEFAULT,
                        help='Pulse tiles dropped at the train/val boundary.')
    parser.add_argument('--epochs', type=int, default=EPOCHS)
    parser.add_argument('--batch-size', type=int, default=BATCH_SIZE)
    return parser.parse_args()


def main():
    """
    Train on the combined training pool (train/val split only), then run TWO
    independent held-out evaluations:

      1. --test-dir: a separate generator run over a disjoint pulse window,
         same 0..6 band range, clean tiles interspersed -- the original
         CHECK 1 / CHECK 2 evaluation.
      2. --paired-test-dir: the same background tile, once clean and once
         with RFI forced onto it (generate_mountain_rfi_data.py
         --paired-test). Skipped with a note if not present, since it is a
         newer, optional addition.

    Only the top N_KEEP = 12 eigenvalues ever reach the model; the SCM
    diagonal is used only by the evaluation-time jump metric, never as a
    model input.
    """
    args = parse_args()

    os.makedirs(MODELS_ROOT, exist_ok=True)
    run_name = args.run_name or os.path.basename(os.path.normpath(args.data_dir[0]))

    print(f"\n{'='*70}")
    print('RFI knee classifier training')
    print(f"{'='*70}")
    print(f"  train region(s)   : {', '.join(args.data_dir)}")
    print(f"  test  region      : {args.test_dir}")
    print(f"  paired test region: {args.paired_test_dir}")
    print(f"  features          : top {N_KEEP} of {M} eigenvalues, linear-normalized then dB")
    print(f"  run name          : {run_name}")

    # ---------------- Training region (amazon + mountain, combined) -------
    train_data = load_rfi_data_dir(args.data_dir, args.max_samples, tag='TRAIN region')
    n_classes = train_data['n_classes']

    print(f"\nTraining region: {len(train_data['labels'])} tiles   "
          f"classes: {n_classes}   channels: {', '.join(train_data['meta']['channels'])}")
    uniq, counts = np.unique(train_data['labels'], return_counts=True)
    for u, c in zip(uniq.tolist(), counts.tolist()):
        print(f"  label {u} ({'clean' if u == 0 else f'knee@{u}'}): {c}")

    idx_train, idx_val = split_train_val(
        train_data['groups'], args.val_frac, args.split_buffer
    )

    model, out_dir = train_model(
        run_name, n_classes,
        train_data['eigen'][idx_train], train_data['global'][idx_train],
        train_data['labels'][idx_train],
        train_data['eigen'][idx_val], train_data['global'][idx_val],
        train_data['labels'][idx_val],
        epochs=args.epochs, batch_size=args.batch_size,
    )

    # ---------------- Held-out test region (disjoint window) --------------
    test_data = load_rfi_data_dir(args.test_dir, args.max_samples, tag='TEST region')
    check_disjoint(train_data['meta'], test_data['meta'])

    uniq, counts = np.unique(test_data['labels'], return_counts=True)
    print(f"\nTest region: {len(test_data['labels'])} tiles")
    for u, c in zip(uniq.tolist(), counts.tolist()):
        print(f"  label {u} ({'clean' if u == 0 else f'knee@{u}'}): {c}")

    results = evaluate(model, test_data, n_classes, run_name, out_dir)

    results['n_train'] = int(len(idx_train))
    results['n_val'] = int(len(idx_val))
    results['train_provenance'] = train_data['meta']
    results['test_provenance'] = test_data['meta']

    # ---------------- Paired mountain test (same tile, clean vs RFI) ------
    try:
        paired_data = load_paired_test_dir(args.paired_test_dir, tag='PAIRED TEST region')
    except FileNotFoundError as exc:
        print(f"\n=== PAIRED CHECK: SAME-TILE CLEAN vs. RFI-OVERLAID ===")
        print(f"  SKIPPED: {exc}")
        print(f"  Generate one with: generate_mountain_rfi_data.py ... --paired-test "
              f"--output-dir {args.paired_test_dir}")
    else:
        results = paired_behavior_check(model, paired_data, out_dir, results)
        results['paired_test_provenance'] = paired_data['meta']

    with open(os.path.join(out_dir, 'eval_results.json'), 'w') as fh:
        json.dump(results, fh, indent=2)
    summary_path = os.path.join(MODELS_ROOT, f'{run_name}_summary.json')
    with open(summary_path, 'w') as fh:
        json.dump(results, fh, indent=2)

    print(f"\nSummary saved to {summary_path}")


if __name__ == '__main__':
    main()